import type { JsonValue, ProtocolDefinition, ProtocolJsonSchema } from "../contract/types.ts";

export const GENERATED_PROTOCOL_HEADER = "// @generated by pi-protocol generate; DO NOT EDIT.";

export function generateProtocolTypes(definition: ProtocolDefinition): string {
  const lines = [
    GENERATED_PROTOCOL_HEADER,
    `// contract-digest: ${definition.contractDigest}`,
    `import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";`,
    "",
    `export const PROTOCOL_NODE_ID = ${JSON.stringify(definition.manifest.node.id)} as const;`,
    "export const PROTOCOL_TARGETS = {",
    ...definition.manifest.provides.map((provide) => `  ${safeProperty(provide.name)}: ${JSON.stringify(`${definition.manifest.node.id}.${provide.name}`)},`),
    "} as const;",
    "",
    `export type ProtocolProvideName = ${definition.manifest.provides.map((provide) => JSON.stringify(provide.name)).join(" | ") || "never"};`,
    "export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;",
    "export type ProtocolBindings = {",
    ...definition.manifest.provides.map((provide) => `  ${JSON.stringify(provide.name)}: ProtocolBinding;`),
    "};",
    "",
  ];
  for (const [name, schema] of Object.entries(definition.manifest.$defs ?? {})) {
    lines.push(`export type ${typeName(name)} = ${schemaType(schema, definition, new Set([name]))};`);
  }
  if (Object.keys(definition.manifest.$defs ?? {}).length) lines.push("");
  for (const provide of definition.manifest.provides) {
    const name = typeName(provide.name);
    lines.push(`export type ${name}Input = ${schemaType(provide.inputSchema, definition, new Set())};`);
    lines.push(`export type ${name}Output = ${schemaType(provide.outputSchema, definition, new Set())};`);
  }
  lines.push("");
  return lines.join("\n");
}

function schemaType(schema: ProtocolJsonSchema, definition: ProtocolDefinition, seen: Set<string>): string {
  if (schema.$ref) {
    const name = schema.$ref.slice("#/$defs/".length).replaceAll("~1", "/").replaceAll("~0", "~");
    return typeName(name);
  }
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ") || "never";
  if (schema.oneOf) return schema.oneOf.map((child) => schemaType(child, definition, seen)).join(" | ");
  const rawType = schema.type;
  if (Array.isArray(rawType)) return rawType.map((type) => type === "null" ? "null" : schemaType({ ...schema, type } as ProtocolJsonSchema, definition, seen)).join(" | ");
  switch (rawType) {
    case "null": return "null";
    case "boolean": return "boolean";
    case "number":
    case "integer": return "number";
    case "string": return "string";
    case "array": return `readonly ${parenthesize(schemaType(schema.items ?? {}, definition, seen))}[]`;
    case "object": {
      const required = new Set(schema.required ?? []);
      const properties = Object.entries(schema.properties ?? {}).map(([key, child]) =>
        `${safeProperty(key)}${required.has(key) ? "" : "?"}: ${schemaType(child, definition, seen)};`
      );
      if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
        properties.push(`[key: string]: ${schemaType(schema.additionalProperties, definition, seen)};`);
      }
      return properties.length ? `{ ${properties.join(" ")} }` : "Record<string, never>";
    }
    default: return "unknown";
  }
}

function literal(value: JsonValue): string {
  return value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string"
    ? JSON.stringify(value)
    : "unknown";
}
function parenthesize(value: string): string { return value.includes(" | ") ? `(${value})` : value; }
function safeProperty(value: string): string { return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value); }
function typeName(value: string): string {
  const output = value.split(/[^A-Za-z0-9]+/).filter(Boolean).map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join("");
  return /^[A-Za-z_$]/.test(output) ? output : `Protocol${output || "Value"}`;
}
