import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { checkProtocolPackage, checkProtocolTree, discoverProtocolPackages } from "../packages/pi-protocol/conformance/index.ts";
import { runCheckCli } from "../packages/pi-protocol/cli/check.ts";
import { diagnoseProtocolRuntime } from "../packages/pi-protocol/cli/doctor.ts";
import { runGenerateCli } from "../packages/pi-protocol/cli/generate.ts";
import { ensureProtocolFabric } from "../packages/pi-protocol/fabric.ts";
import { parseProtocolManifest } from "../packages/pi-protocol/contract/index.ts";

const root = mkdtempSync(join(tmpdir(), "pi-protocol-conformance-"));
const first = join(root, "outer", "nested-extension");
mkdirSync(join(first, "prompts"), { recursive: true });
const manifest = JSON.parse(readFileSync(new URL("./fixtures/contracts/valid-v1.json", import.meta.url), "utf8"));
manifest.node.id = "conformance_fixture";
writeFileSync(join(first, "pi.protocol.json"), `${JSON.stringify(manifest, null, 2)}\n`);
writeFileSync(join(first, "package.json"), JSON.stringify({
  name: "@tests/conformance-fixture",
  version: "1.0.0",
  dependencies: { "@kybernetria/pi-protocol": "^2.0.0" },
  piProtocol: { generated: "src/protocol.generated.ts" },
}, null, 2));
writeFileSync(join(first, "prompts", "agent.md"), "Use the protocol carefully.\n");
writeFileSync(join(first, "pi.agents.json"), JSON.stringify({ schemaVersion: 1, agents: { worker: { prompt: "prompts/agent.md", tools: ["protocol"], protocolAccess: { targets: ["conformance_fixture.echo"] } } } }));

assert.equal((await discoverProtocolPackages(root)).length, 1, "recursive discovery must find nested packages");
assert.equal(checkProtocolPackage(first).issues.some((issue) => issue.code === "GENERATED_MISSING"), true);
assert.equal(await runGenerateCli([first]), 0);
const generated = readFileSync(join(first, "src", "protocol.generated.ts"), "utf8");
assert.match(generated, /@generated by pi-protocol generate/);
assert.match(generated, /contract-digest: sha256:/);
assert.match(generated, /conformance_fixture\.echo/);
assert.match(generated, /export type EchoInput/);
assert.equal(await runGenerateCli([first, "--check"]), 0);
assert.equal(checkProtocolPackage(first).ok, true);
writeFileSync(join(first, "src", "protocol.generated.ts"), `${generated}// drift\n`);
assert.equal(checkProtocolPackage(first).issues.some((issue) => issue.code === "GENERATED_DRIFT"), true);
assert.equal(await runGenerateCli([first]), 0);
assert.equal((await checkProtocolTree(root)).every((result) => result.ok), true);
assert.equal(await runCheckCli([root, "--recursive"]), 0);

const legacy = join(root, "legacy");
mkdirSync(legacy);
const legacySource = readFileSync(new URL("./fixtures/contracts/valid-v02.json", import.meta.url), "utf8");
writeFileSync(join(legacy, "pi.protocol.json"), legacySource);
writeFileSync(join(legacy, "package.json"), JSON.stringify({ name: "@tests/legacy", version: "1.0.0", dependencies: { "@kybernetria/pi-protocol": "^2.0.0" } }));
assert.equal(checkProtocolPackage(legacy).issues.some((issue) => issue.code === "MANIFEST_INVALID"), true);
const legacyAllowed = checkProtocolPackage(legacy, { allowLegacy: true });
assert.equal(legacyAllowed.ok, true);
assert.equal(legacyAllowed.issues.some((issue) => issue.code === "LEGACY_MANIFEST"), true);

const outside = mkdtempSync(join(tmpdir(), "pi-conformance-outside-"));
writeFileSync(join(outside, "outside.md"), "private");
symlinkSync(join(outside, "outside.md"), join(first, "prompts", "escape.md"));
const escapedProfiles = JSON.stringify({ schemaVersion: 1, agents: { bad: { prompt: "prompts/escape.md" } } });
writeFileSync(join(first, "pi.agents.json"), escapedProfiles);
assert.equal(checkProtocolPackage(first).issues.some((issue) => issue.code === "PROFILE_INVALID"), true);
writeFileSync(join(first, "pi.agents.json"), JSON.stringify({ schemaVersion: 1, agents: { worker: { prompt: "prompts/agent.md" } } }));
symlinkSync(root, join(first, "cycle"));
assert((await discoverProtocolPackages(root)).length === 2, "symlink cycles must terminate without duplicates");
await assert.rejects(() => discoverProtocolPackages(root, { maxDirectories: 1 }), /directory limit/);

const fabric = ensureProtocolFabric();
const definition = parseProtocolManifest(JSON.stringify(manifest));
const registration = fabric.install(definition, { handlers: { echo: (input) => input } }, {
  packageId: "@tests/conformance-fixture",
  packageVersion: "1.0.0",
  sourcePath: first,
  buildId: "test-build",
});
const healthy = diagnoseProtocolRuntime(fabric);
assert.equal(healthy.ok, true);
assert.equal(healthy.fabric.registrations[0]?.contractDigest, definition.contractDigest);
assert.equal(healthy.fabric.registrations[0]?.sourcePath, first);
assert.equal(healthy.host?.runtimeCopies.length, 1);
fabric.register({
  node: {
    nodeId: "legacy_raw",
    purpose: "doctor fixture",
    provides: [{ name: "run", description: "raw fixture", inputSchema: { type: "object" }, outputSchema: { type: "object" }, execution: { type: "handler", handler: "run" } }],
  },
  handlers: { run: () => ({}) },
});
const deprecated = diagnoseProtocolRuntime(fabric);
assert(deprecated.issues.some((issue) => issue.code === "UNOWNED_REGISTRATION"));
assert(deprecated.issues.some((issue) => issue.code === "DEPRECATED_COMPATIBILITY"));
fabric.unregister("legacy_raw");
await registration.dispose();

console.log("recursive conformance, deterministic generation, and runtime doctor work");
